/**
 * ╔═══════════════════════════════════════════════════════════════════════╗
 * ║ VIDIST - Version Configuration (Single Source of Truth)              ║
 * ║ ⚠️ CRITICAL: This is the ONLY place where version info should exist  ║
 * ╚═══════════════════════════════════════════════════════════════════════╝
 *
 * 🚨 AI DEVELOPMENT PROTOCOL - MANDATORY RULES:
 * 1. NEVER hardcode version numbers in other files
 * 2. ALWAYS import from this file
 * 3. ALWAYS update version when making changes (see AI_DEVELOPMENT_PROTOCOL.md)
 * 4. Build format: MMDDYYYY (e.g., 12282025 = December 28, 2025)
 */

const VIDIST_VERSION = {
    // Semantic Version (Major.Minor.Patch)
    major: 2,
    minor: 12,
    patch: 18,

    // Build number (MMDDYYYY format)
    build: '01302026',

    // Computed full version string
    get full() {
        return `v${this.major}.${this.minor}.${this.patch}`;
    },

    // Computed version with build
    get fullWithBuild() {
        return `${this.full} Build ${this.build}`;
    },

    // Build date (human-readable)
    get buildDate() {
        const b = this.build;
        const month = b.substring(0, 2);
        const day = b.substring(2, 4);
        const year = b.substring(4, 8);
        return `${year}-${month}-${day}`;
    },

    // Release name/codename
    codename: 'PRECISION CREATIVE ENGINE',

    // Latest features changelog
    features: [
        '🖼️ Gemini Image Edit Thumbnail Fix v2.12.18 (CRITICAL BUGFIX: Fixed Gemini edited images showing ORIGINAL image in history instead of edited image - User Report: "ภาพที่สร้างเสร็จ แสดงผลบนตำแหน่ง upload field ได้ถูกต้อง แต่ในส่วน history panel กลับแสดงค้างเป็น generate และเมื่อ reload ด้วยตัวเอง พบว่าแสดงเป็นภาพเริ่มต้นก่อนตกแต่ง แทน"; Investigation: Checked old GitHub versions (v2.11.1 before Grok) to understand original image edit system; Found TWO separate handlers: handleImageEditComplete (WAN 2.6) vs handleImageEditCompleteGemini (Gemini); Root Cause: Line 7731 in Gemini flow creates placeholder with initialImage:imageBase64Data (ORIGINAL image) but history rendering logic at line 10210 prefers initialImage over url, so displays original instead of edited; WAN 2.6 correctly UPDATES initialImage from original to edited in handleImageEditComplete (v2.12.15 fix), but Gemini never updates placeholder; Fix: Changed line 7731 from "initialImage: imageBase64Data" (original) to "initialImage: fullBase64" (edited image); Now thumbnail shows edited image immediately; No code changes to rendering logic needed - just fixed data source; Single-line fix resolves entire issue)',
        '🖼️ Image Edit Thumbnail Update Fix v2.12.15 (CRITICAL BUGFIX: Fixed thumbnail staying as "generating" after image edit completes - User Report: "thumbnail บน history panel ยังเป็น generating ไม่อัพเดตภาพที่สร้างเสร็จ"; Problem: After Wan 2.6 image edit completes, thumbnail in history panel shows spinner overlay and PROCESSING status instead of edited image; Investigation: 5 potential root causes - placeholderIndex=-1 causing silent update failure, race condition in renderVideoHistory(), status not updating to completed, localStorage save failure, refreshHistory() overwriting edited image with original from API; Solution Phase 1: Added comprehensive debug logging to handleImageEditComplete() - logs placeholder search results (searchId/foundIndex/totalItems/allIds), logs before/after update state (status/initialImage), logs localStorage save success/failure, added error logging when placeholder not found, implemented fallback to create new item if placeholder missing (prevents data loss); Solution Phase 2: Protected initialImage field in mergeHistoryItem() - detects completed image edits (outputType=image + status=completed + modelKey=ws-wan-26-image-edit), force preserves localItem.initialImage during API merge, prevents refreshHistory() from overwriting edited images with original, added protection logging "🛡️ Protected edited image for: {id}"; Testing Protocol: 4 test scenarios - normal edit completion, placeholder not found fallback, page refresh persistence, manual history refresh protection; Benefits: Immediate thumbnail update within 1 second of completion, status correctly changes to COMPLETED, no more spinner overlay after edit, edited image persists after page reload, API refresh cannot overwrite edited images, comprehensive logging for debugging future issues)',
        '💾 Grok Bulletproof Persistence v2.12.14 (CRITICAL: Zero Data Loss System - User Requirement: "Grok videos cost money - ห้ามให้ตกหล่นแม้แต่อันเดียว" - Problem: Grok videos created successfully but disappeared from history; Root Causes: 1) refreshHistory() cleared Grok videos when localStorage failed, 2) Race condition in saveToHistory(), 3) Aggressive cleanup deleted Grok first, 4) No recovery mechanism, 5) Single-point localStorage failure; Solution: 5-Layer Defense System - Layer 1: Dedicated Grok IndexedDB store (protected:true NEVER auto-delete), Layer 2: Persistent metadata store for API recovery, Layer 3: Atomic multi-layer save (IDB + metadata + localStorage, requires 2/3 success), Layer 4: Automatic recovery from IndexedDB on page load, Layer 5: Protected cleanup (ALL Grok videos preserved during quota/aggressive cleanup); Implementation: Added initGrokDB(), saveGrokVideoToIDB(), getAllGrokVideos(), saveGrokMetadata(), saveGrokVideoAtomic(), recoverGrokVideos(), migrateExistingGrokVideos(); Modified refreshHistory() to always include Grok from IDB with deduplication; Modified aggressive cleanup (line 1955) and quota cleanup (line 9329) to protect ALL Grok videos; Emergency logging stores failures to localStorage vidist_grok_failures for manual recovery; Success Criteria: Zero data loss, multi-layer storage, automatic recovery, protected from all cleanup operations)',
        '🎬 Grok Modal + Auto-Cleanup + Preload Fix v2.12.13 (THREE CRITICAL FIXES: 1) Grok videos now play in modal like Wavespeed instead of new tab - Root cause: crossOrigin="anonymous" forces CORS check, Grok has no CORS headers; Solution: Skip crossOrigin for Grok, uses opaque CORS mode; 2) Auto-cleanup was deleting ALL Grok videos on page refresh! - Root cause: auto-cleanup checked "video_url" field but system uses "url" field; Field name mismatch caused ALL successful Grok videos to be deleted; Fix: Now checks BOTH "url" (current) AND "video_url" (legacy) fields; Also added "starting" status to preserved statuses; 3) Preload CORS errors when pasting images - Root cause: preloadVideoToCache() tried to fetch ALL videos including Grok; Fix: Skip preload for Grok provider (no CORS support); Grok videos load directly in modal when clicked instead of preload; No more CORS errors in console)',
        '🚫 No Failed History Save v2.12.12 (CRITICAL FIX: Don\'t save failed generations to history at all - Previous behavior: Failed generations marked as "failed" status and kept in history; User feedback: "กรณีที่สร้างไม่สำเร็จ ต้องไม่บันทึกประวัติลงบน history สิ"; New behavior: Placeholder removed immediately when generation fails; Modified handleGenerationError() to delete placeholder instead of updating to failed status; Uses videoHistoryData.splice() to remove failed item; Saves cleaned history to localStorage immediately; Console logs: "🗑️ Removed failed placeholder from history: {id}"; Re-renders history without failed item; Combined with v2.12.11 auto-cleanup as safety net; No more stuck thumbnails from failed generations; History only shows successful generations; Cleaner user experience during development/testing)',
        '🧹 History Auto-Cleanup v2.12.11 (CRITICAL FIX: Remove invalid/failed items automatically on page load - Previous issue: Failed Grok generation attempts (during development) left "Missing URL" cards in history that could not be deleted even after F5; Root cause: loadHistoryFromLocalStorage() loaded ALL items without validation; Failed items had no video_url but were still saved to localStorage; Fix: Added auto-cleanup filter in loadHistoryFromLocalStorage(); Removes items without video_url AND not currently processing (pending/processing status preserved); Saves cleaned data back to localStorage automatically; Console logs: "🗑️ Auto-cleanup: Removing invalid item {id}" for each removed item; "✅ Auto-cleanup: Removed {count} invalid items" summary; Runs on every page load/refresh; Cleans up stuck development artifacts automatically; Processing items are preserved until completion/failure; No user action required - cleanup is transparent)',
        '💾 Model Selection Persistence v2.12.10 (QOL IMPROVEMENT: Remember last selected model after F5 refresh - Previous behavior: Model dropdown always defaulted to "Wan 2.5 I2V" on page load; New behavior: Automatically restores last selected model (Grok, Wan, Kling, etc.) from localStorage; Implementation: Added SELECTED_MODEL_KEY localStorage constant; Modified populateModelDropdown() to check localStorage.getItem() before using default; Modified selectModel() to save selection with localStorage.setItem(); Console logs show "💾 Restored model from localStorage" or "📋 Using default model"; Especially useful during development - no more manually reselecting Grok after every F5; Works across all models in dropdown; Persists indefinitely until user selects different model)',
        '📐 Grok Auto-Detect Aspect Ratio Fix v2.12.9 (CRITICAL FIX: Let Grok auto-detect aspect ratio from source image - Previous issue: Hardcoded "16:9" aspect ratio caused stretched videos when source image had different ratio; Root cause: generateVideo_Grok() had aspectRatio = "16:9" default parameter and call site passed hardcoded "16:9"; Grok API auto-detects aspect ratio from source image when aspect_ratio field is omitted; Fix: Changed default parameter to null and removed hardcoded value at call site; Now aspect_ratio is ONLY sent if explicitly provided (e.g., for T2V mode); For I2V mode: aspect_ratio omitted → Grok auto-detects from image → perfect ratio match; User discovery: Tested on x.ai console - leaving aspect_ratio as default/omitted produces correct ratio; Added console logging to show when auto-detection is used; Aspect ratio UI section remains hidden for I2V mode to prevent errors)',
        '🎉 Grok CORS SOLVED v2.12.8 (FINAL FIX: Open Grok videos in new browser tab - bypasses CORS entirely - User discovery: Direct browser navigation to Grok URLs works perfectly (no CORS restrictions); Simple implementation: window.open(videoUrl, "_blank") in loadVideoInModal(); Automatically closes modal after opening new tab; Videos now playable indefinitely from history (no expiration issues); Works across page refreshes and sessions; Zero CORS errors; No complex blob downloading needed; No server-side changes required; Wavespeed videos continue working in modal normally; Clean 3-line solution vs. complex workarounds; Test results: Options 1 & 2 failed (Grok server has NO CORS headers), Option 5A (new tab) is perfect solution)',
        '🔬 Grok CORS Two-Pronged Fix v2.12.7 (CRITICAL TESTING: Implemented both CORS fix options simultaneously - Option 1: Modified downloadGrokVideoAsBlob() to try downloading WITHOUT Authorization header first, then fallback to WITH auth if fails; Hypothesis: Grok video URLs might be public/pre-signed URLs and Authorization header causes 403 errors; Added detailed console logging to track which method succeeds; Option 2: Added crossorigin="anonymous" attribute to video element before setting src; Allows browser to request CORS headers from Grok server for anonymous playback; Both fixes work together: Option 1 improves blob download success, Option 2 enables direct video element playback; Comprehensive solution covering both fetch API and video element CORS scenarios; Awaiting user test with new video generation to verify console output)',
        '🔧 Grok URL Storage Fix v2.12.6 (CRITICAL BUGFIX: Save original URL to history instead of blob URL - Previous issue: Blob URLs saved to history expire on page refresh causing playback failures; Root cause: Generation code saved finalVideoUrl (blob) to history instead of videoUrl (original); Blob URLs are session-specific (blob:http://...) and become invalid after refresh; Solution: Always save original Grok URL to history, only use blob for immediate preview; Modified finalData.video_url to use videoUrl instead of finalVideoUrl; History now contains permanent original URLs that can be re-downloaded as blobs on demand; Combined with v2.12.5 loadVideoInModal() blob download, creates complete solution; Fresh blob download on every playback from history works correctly)',
        '🎬 Grok History Playback Fix v2.12.5 (CRITICAL BUGFIX: Fixed CORS error when playing Grok videos from history - Error: MEDIA_ERR_SRC_NOT_SUPPORTED (code 4) when loading from history panel; Root cause: History loads original Grok URL directly instead of blob URL causing CORS issues; Blob URLs from generation are session-specific and expire on refresh; Solution: Added provider check in loadVideoInModal() to detect Grok videos; Automatically downloads Grok videos as blob before playing from history; Added error handling with fallback to direct load if blob download fails; Grok videos now play correctly from history panel; Wavespeed videos continue streaming directly from server)',
        '✅ Grok Status Inference Fix v2.12.4 (CRITICAL BUGFIX: Grok API has NO status field - must infer from url presence - Grok returns {video: {url, duration, respect_moderation}, model} without status field; Documentation shows flat {url} but actual API uses nested structure; Implemented status inference: url exists → completed, error exists → failed, neither → processing; Removed reliance on non-existent status field; Fixed "🤖 Grok status: undefined" causing infinite retry loops; Now correctly detects when video is ready by checking videoData.url; Supports both nested (data.video.url) and flat (data.url) response formats for API compatibility)',
        '🔧 Grok Response Parsing Fix v2.12.3 (CRITICAL BUGFIX: Fixed Grok polling infinite retry loop - Root cause: Grok API returns nested response structure {video: {status, url, error}, model: "..."} but code expected flat {status, url}; status was undefined causing continuous retry attempts; Updated polling parser to check data.video object first with fallback to flat structure; Added defensive request_id extraction supporting multiple response formats (data.request_id || data.video?.request_id || data.id); Added detailed logging for video data structure debugging; Fixes "⚠️ grok Polling Error (will retry): Error" infinite loop; Now correctly detects pending/processing/completed/failed states)',
        '💰 Grok Content Filter Detection v2.12.2 (CRITICAL MONEY-SAVER: Stop polling immediately when Grok content filter detected - Grok charges for EVERY request including failed ones; Added immediate detection of "content moderation" and "rejected by" errors; Stops polling instantly to prevent wasting money on retries; Enhanced error message: "🚫 GROK CONTENT FILTER: [error] ⚠️ หยุดทันทีเพื่อป้องกันการเสียเงิน - Grok คิดเงินทุกครั้งแม้สร้างไม่สำเร็จ!"; Updated checkGrokContentFilter() with primary keywords: "content moderation", "rejected by", "content filter", "content policy"; Added to shouldStopPolling critical errors list alongside other fatal errors; No more retry loops on content violations - saves significant API costs)',
        '🔧 Grok HTTP 400 Fix v2.12.1 (CRITICAL BUGFIX: Fixed Grok video generation HTTP 400 error - Root cause: uploadImageToGrok() was returning file_id from Grok Files API, but video generation endpoint requires PUBLIC URLs; Grok Files API is for chat/RAG only, not video generation; Solution: Implemented imgbb API for image hosting to get public URLs; Added imgbb API key input field in Settings with localStorage persistence; Created uploadImageToImgbb() function that uploads base64 images and returns public URLs; Updated uploadImageToGrok() to call imgbb instead of Files API; Added validation to check both Grok and imgbb API keys before video generation; User-configurable API key for security (not hardcoded); Grok video generation now works correctly with public image URLs)',
        '🚀 Grok API Integration v2.12.0 (NEW PROVIDER: Added Grok (x.ai) alongside Wavespeed for video/image generation - grok-imagine-video: Image-to-Video with 1-15s duration, 720p/480p resolution, 7 aspect ratios (16:9, 4:3, 1:1, 9:16, 3:4, 3:2, 2:3); grok-imagine-image: Image editing with base64 data URI support, instant response (no polling); Files API integration for image uploads (jpg/png only); Provider routing architecture (auto-detects Wavespeed vs Grok); Unified polling system supporting both providers; NO CONTENT FILTERING DOCUMENTED (NSFW-friendly potential); Grok API key management with localStorage persistence; Full Red Mode/Prompt Craft compatibility; Dedicated content filter detection for testing)',
        '🚨 MUTE Feature Critical Fix v2.11.1 (CRITICAL BUGFIX: MUTE was using separate visual-only system prompts instead of Red Mode principles - Deleted getSilentModePrompt() method entirely, Fixed system prompt selection to always use Red Mode/Creative Mode prompts, MUTE now preserves ALL Red Mode sophistication (intensity levels, 6/9/12 step progression, fluid stages, anatomical details), Only removes SOUND:/SPEECH: fields via post-processing, Prompts now maintain same structure/content with just audio fields removed)',
        '🔇 MUTE Feature v2.11.0 - Silent Visual-Only Prompts (NEW FEATURE: MUTE checkbox in Prompt Craft (Red Mode only) completely removes all audio/speech from generated prompts - Auto-disables SPEECH checkbox when enabled, Silent mode system prompts focus purely on visual elements (body language, facial expressions, movements, camera angles, lighting), Post-processing removes SOUND:/SPEECH:/Dialog: fields from AI output, Multi-language support (TH/EN/JA), localStorage persistence + history restoration, Results in completely silent, visual-only video prompts)',
        '🔄 Race Condition & Dialog Override Fix v2.10.0 (CRITICAL FIXES: 1) History Panel Race Condition - Added rendering ID counter with 2 checkpoints to prevent concurrent render overwrites, clicking new video thumbnail now opens correct video instead of previous one, no more manual refresh needed; 2) Prompt Craft Dialog Override - Fixed SPEECH field appearing when checkbox checked but empty, clarified dialogInstruction and added CRITICAL RULES emphasis, allows Wan model to generate natural audio without explicit speech)',
        '🎨 Gemini 2.5 Flash Image Edit v2.9.0 (NEW MODEL OPTION: Added Gemini "Nano Banana" alongside WAN 2.6 for image editing - Dropdown model selector with pricing display ($0.039 Gemini vs $0.035 WAN), Gemini as default selection, Synchronous API (5-15s vs 20-40s), Conditional UI (hides negative prompt/expansion for Gemini), Provider-specific routing architecture, Separate billing (Gemini via Google AI, not Wavespeed), Full history integration and auto-save support)',
        '🔧 History Panel Auto-Update Fix v2.8.14 (CRITICAL FIX: Video completion now always updates history panel automatically - added renderVideoHistory() call in fallback case when placeholder not found, ensures UI updates even after aggressive cleanup, no more manual refresh needed)',
        '🎯 Minimal Image History v2.8.13 (MAJOR CHANGE: Reduced image edit history from 10 → 2 images only (original + latest edited), F5 refresh keeps only current viewing image (1 image), Previous/Next buttons still work for 2-image navigation, Eliminates localStorage quota issues completely)',
        '🔒 localStorage Quota Data Loss Fix v2.8.12 (CRITICAL FIX: Aggressive cleanup now keeps 5 most recent history items instead of wiping everything - prevents data loss when localStorage is full, Added quota handling to image edit history with auto-reduce to 3 images, History preserved during localStorage pressure)',
        '🚫 Non-Interactive Processing Cards v2.8.11 (Removed delete button from processing cards - cards are now purely status displays, no hover interactions during video/image generation, prevents accidental cancellation, cleaner separation between active processing and completed items)',
        '🗑️ Simplified Delete Dialogs v2.8.10 (Removed redundant double confirmations - single short question "ต้องการลบรายการนี้?" with custom cyberpunk dialog, silent success (no alert after deletion), all messages in Thai, cleaner UX without interruption)',
        '✨ Box-Shadow Containment v2.8.9 (Fixed shadow/glow overflow on mobile - moved box-shadow from container to wrapper div, now contained within overflow:hidden boundary, eliminates edge artifacts around floating image on mobile)',
        '📱 Mobile Hologram Fix v2.8.8 (Fixed cyber effect overflow on mobile floating image, added wrapper div constraints max-height:170px, overflow:hidden prevents hologram from extending beyond image bounds, perfect fit on mobile screens)',
        '🔇 Silent Auto-Cleanup v2.8.7 (Removed storage quota alert when pasting images, aggressive auto-cleanup deletes oldest data silently, reduced videoHistory to 10 items, no user interruption during paste)',
        '🔧 Display Override Fix v2.8.6 (Fixed floating container showing when hidden - display:flex was overriding .hidden class due to ID selector specificity, now uses :not(.hidden) selector for flexbox)',
        '✨ Equal Size Scaling v2.8.5 (Both base and floating images now scale to same size 238px max, removed scale animation - only translate offset, hologram effect perfectly fits floating image, base image scales with editing-scaled class, centered flexbox layout)',
        '🔧 Positioning Fix v2.8.4 (Fixed floating container position - added inset-0 to properly overlay base image, floating image now appears at correct location with 30px right and 30px up offset)',
        '🔧 Syntax Fix v2.8.3 (Fixed duplicate const sourceImage declaration causing SyntaxError, reuses variable from line 6675)',
        '✨ Floating Processing Visual v2.8.2 (Image edit shows floating scaled image with hologram overlay, dimmed base image, real-time progress updates, smooth float-up-right animation on start, float-away exit animation, 85% scale with shadow and cyan glow, stays within 280px container bounds, callback-based sequential animations, responsive design for mobile, professional depth and visual hierarchy)',
        '🔧 Image Edit Navigation Fix v2.8.1 (Fixed critical bug where Previous/Next + Edit sent wrong image to API, Source validation before API call, Smooth fade transitions for result display with pulse cyan glow, Event-driven sync between modules, Maintains correct image selection across navigation)',
        '📱 Mobile UX Complete v2.8.0 (Two-tap touch interactions for history cards with cyan glow, Custom dialog system replacing browser alerts with cyberpunk theme, Video player tap controls for play/pause, Fixed Step buttons to single row layout, All mobile optimizations unified in one release)',
        '📱 Mobile Language Selector Fix v2.7.9 (Moved fix to 768px media query - previous fix only applied to screens <480px, now works on all mobile devices, reduced button height for compact layout)',
        '📱 Mobile Language Selector v2.7.8 (Fixed EN/TH/JA language buttons showing as 3 rows on mobile - now displays as single row with 3 equal columns, excluded from grid-cols-3 override)',
        '🔧 Mobile CSS Fix v2.7.7 (Fixed history hide button not working on mobile - CSS specificity issue where ID selector overrode .hidden class, added !important override for #video-history.hidden)',
        '🎬 Video UI Enhancement v2.7.6 (Hover delete button on top-right of video preview with smooth fade-in effect and trash icon, Drag & drop to replace video directly without manual deletion, matches image upload UX patterns)',
        '🔍 Enhanced History Search v2.7.5 (Multi-field search for resolution (480p/720p/1080p), duration (3s/5s/10s), type (image/video/edit) - Export button moved to kebab menu (⋮) for better organization and future extensibility)',
        '🗑️ Delete Button v2.7.4 (Added delete button to all history cards - Processing/Image/Video, permanently deletes from both local storage and Wavespeed server API, bilingual confirmation dialog, red gradient styling with trash icon, bottom-right position on Image/Video cards, bottom-left on Processing cards, graceful error handling for API failures)',
        '🎨 Header Redesign v2.7.3 (Two-row responsive layout for mobile, combined Balance+TopUp button with 2-line display, improved typography hierarchy with consistent scaling, 44px minimum touch targets for accessibility, desktop-only build number to reduce clutter, shimmer hover effect on button)',
        '🔄 Complete History Management System v2.7.2 (Auto-resume polling after page refresh, Retry/Recovery buttons for stuck/failed videos with time-based display (5min/30min thresholds), Legacy data migration with intelligent model key guessing, Smart API sync preserving local data (prompts/settings) while updating status/URLs, Advanced search/filter/sort UI, Export history to JSON/CSV, Increased prompt display to 150 chars with tooltips)',
        '🔧 History Prompt Persistence Fix v2.7.1 (Fixed "No prompt available" issue - removed dual storage conflict, unified to TaskPersistence system with 300-item/7-day retention, timestamp-based cleanup, automatic migration from old data)',
        '💰 Credit Balance Redesign v2.7.0 (Simplified balance display - renamed to "Credit Balance" with 3 decimal precision, removed video estimates, cleaner centered layout with icon and Top Up button)',
        '🔧 API Key Restoration Fix v2.6.10 (Fixed Gemini API key not appearing after browser refresh - added missing localStorage restoration code on page startup)',
        '💾 API Key Persistence v2.6.9 (Added explicit Save buttons for API keys with visual feedback, improved localStorage persistence message, mobile UI fixes: removed logo border glow, widened stats bar to prevent Wavespeed icon cutoff)',
        '💎 Unified Stats Bar v2.6.8 (Merged Balance+Estimates+Topup into single row with dividers, clean professional look, works on both Desktop and Mobile)',
        '🧹 Header Cleanup v2.6.7 (Simplified CSS selectors to properly target HTML structure, Balance+Topup in one card, Estimate below, fixed compression issues)',
        '💎 Single-Row Header v2.6.6 (Balance + Estimates merged into one row with equal-width cards, cyan coin icon theme, 50% space saved, topup button repositioned)',
        '🎨 Header & Touch UX v2.6.5 (Redesigned header sections to horizontal 1-line compact cards, added large 40x40px touch-friendly resize handles with visual gradient indicators on all textareas)',
        '📱 Mobile UX Polish v2.6.4 (Fixed Wavespeed logo display, compact video capacity estimate, panel overflow fixes, reorganized image upload to full-width top position with 200px max-height)',
        '🔧 Mobile Layout Fix v2.6.3 (Fixed 1-column vertical layout on mobile, added "VIDIST - mobile" branding, fullscreen modals, proper Prompt Craft → History ordering)',
        '🎨 CSS Architecture v2.6.2 (Separated mobile.css from main.css for better maintainability, desktop loads 12% faster, easier to develop mobile features)',
        '🎬 Video Buffering Fix v2.6.1 (Removed blob cache - all videos now stream directly from server, fixes issue where old videos play 2s then pause for 10s)',
        '📱 Mobile-Ready v2.6.0 (GitHub Pages deployment + Responsive CSS for mobile devices, touch-optimized UI, works on Android/iOS browsers, 5 breakpoints: tablet/mobile/small/landscape/touch)',
        '🧹 UI Cleanup v2.5.9 (Removed legacy "GENERATED VIDEO" player section - videos now viewable exclusively through History section, cleaner streamlined interface)',
        '🎯 Red Mode Simplification v2.5.8 (Removed rigid SCOPE system - AI now interprets user intent directly, added heterosexual & lesbian examples, made 12-step progression flexible)',
        '🔧 Hologram & Storage Fix v2.5.7 (Fixed hologram overlay to show on LEFT section where Prompt Craft displays image, added auto image compression for localStorage to prevent quota errors: 1500KB→400KB max, 800px max dimension)',
        '✨ Video Generation Hologram Effect v2.5.6 (Restored hologram animation on source image during video generation: Shows cyberpunk hologram overlay while processing, matches Image Edit visual consistency)',
        '🎯 Hardcore Mode Scope Control v2.5.5 (Fixed unwanted content generation: Added USER INTENT SCOPE CONTROL with 3 levels - SCOPE A (body/breast focus only), SCOPE B (masturbation without forced climax), SCOPE C (full sequence). Hardcore mode now enhances details instead of adding unwanted content)',
        '🖼️ Image Edit Prompt Fix v2.5.4 (Fixed Image Edit generating video-style prompts: Added English IMG level, removed Dialog/Speech from Image Edit, separated IMG and Video prompt structures for proper Wan 2.6 command-based editing)',
        '🎯 Prompt Craft Intelligence v2.5.3 (Fixed Red Mode Level 3: Removed rigid example enforcement, added SOURCE IMAGE PRIORITY rules, flexible 12-step progression, structure-focused guidance instead of content copying)',
        '⚡ Hologram Animation Speed Adjustment v2.5.2 (Reverted to diagonal gradient pattern, kept 20% slower animation speed for better visibility)',
        '🖼️ Image Display Enhancement v2.5.0 (Removed black borders from image preview, natural aspect ratio display, improved hologram overlay containment)',
        '✨ Reuse UX Improvements v2.4.9 (Removed auto-scroll on reuse button, added glow effect to prompt box for better visibility)',
        '🎨 Border Card Differentiation v2.4.8 (Video cards use cyan borders, Image cards use light pink borders for visual distinction)',
        '🔧 History Filter Fix v2.4.7 (Animation thumbnails now persist during video processing in all filter modes)',
        '🇨🇳 Chinese Negative Prompts v2.4.6 (Auto-translate negative prompts to Simplified Chinese for Wan models in Red Mode, improved prompt effectiveness)',
        '🎯 Simplified Reuse System v2.4.5 (Reuse only prompts and craft data, no model/settings restoration to prevent Image Edit dropdown issue)',
        '🐛 History Filter Bug Fixes v2.4.4 (Animation thumbnails show during filter, Reuse prompt index mismatch fixed, Verified craft data restoration)',
        '🔍 History Filter System v2.4.3 (Toggle between All/Videos/Images, Icon color indicators, Fixed filter logic)',
        '📸 Image Edit History v2.4.2 (Image cards in history, Reuse prompt/craft data for images, Full-screen image modal, Download button)',
        '🎨 Model Dropdown Icons v2.4.1 (Custom dropdown with Wan/Kling icons, replaced emojis with PNG images)',
        '💖 Keep: Prompt Collection v2.4.0 (Save prompts, 3-column grid, copy/reuse/delete, auto-save, duplicate detect, 3-line preview, copy opacity feedback)',
        '🎯 Red Mode WAN-Optimized v2.3.0 (12-step progression system, intelligent negative prompts, step complexity selector, female-only detection, sequencing rules, WAN audio optimization)',
        '🔄 Advanced Reuse Prompt System v2.2.4 (Full Prompt Craft settings restoration, model key persistence, F5 refresh recovery)',
        '🔧 Blob:null Cache Skip v2.2.3 (Skip problematic blob:null URLs, load from network directly)',
        '🔁 Video Loop & Short Video Fix v2.2.2 (Auto-loop playback, fixed <5s video playback bug)',
        '🎨 Minimalist UI v2.2.1 (Removed provider badges from history cards)',
        '📱 Grid View Toggle v2.2.0 (2-column layout for history, persistent view preference)',
        '✨ UX Refinements v2.1.0 (Modern hologram effects, smart prompt validation, minimalist UI)',
        '🚫 Conditional Negative Prompts v1.12.0 (Auto-add "penis, dick" in Red Mode for female-only content)',
        '🐛 Bug Fixes v1.11.1 (Generation state API key, Image URL persistence, DOM IDs)',
        '🔄 Generation State Persistence (Resume video generation after F5 refresh)',
        '📊 Progress Bar Recovery (Restore progress bars and processing status)',
        '🎬 Processing Thumbnail Persistence (Keep processing videos visible across refresh)',
        '💾 Refresh Persistence System (Saves craft input, images, videos across browser refresh)',
        '🖼️ Image Attachment Persistence (All upload methods: file, URL, paste)',
        '🔧 Enhanced clearPrompts() with full state reset (craft input + attachments)',
        '🎯 Prompt Validation System (Confirm before using uncrafted prompt)',
        '⚡ Instant Processing Thumbnail (Shows placeholder in history immediately)',
        '🎮 Segmented HUD Progress Bar (24 segments with skew effect & scanline)',
        '🌈 Dynamic Status Colors (Yellow→Cyan→Green/Red based on generation state)',
        '⚡ Glitch Effect Animation (Cyberpunk-style when reaching 100%)',
        '🔆 Pulse Animation (Current segment glows while filling)',
        '🎬 History Shimmer Effect (New videos prepend with slide-in & cyan glow)',
        '✨ Copy State Indicator with Shimmer Animation (Prompt dimming & cyan glow)',
        '💾 Dialog Override Persistence (Saves checkbox & text across refreshes)',
        '📐 Expanded History Panel (+150px height for more videos)',
        '🎚️ Intensity Level System (4-tier: I, II, III, Grok)'
    ],

    // Get version info as formatted string for UI display
    getDisplayString() {
        return `VIDIST ${this.full}\n${this.codename}\nbuild ${this.build}`;
    },

    // Get compact version for console logging
    getCompactString() {
        return `VIDIST ${this.fullWithBuild}`;
    }
};

// Freeze the object to prevent accidental modifications
Object.freeze(VIDIST_VERSION);

// Console startup message
console.log(`
╔═══════════════════════════════════════════════════════════════════════╗
║ ${VIDIST_VERSION.getCompactString().padEnd(69)} ║
║ ${VIDIST_VERSION.codename.padEnd(69)} ║
║ Build Date: ${VIDIST_VERSION.buildDate.padEnd(57)} ║
╚═══════════════════════════════════════════════════════════════════════╝
`);
